
const slikeContainer = document.getElementById('slike-container');

const slike = [
    'slike/slika1.jpg',
    'slike/slika2.jpg',
    'slike/slika3.png',
    'slike/slika4.png',
    'slike/slika5.jpeg',
    'slike/slika6.png',
    'slike/slika7.png',
    'slike/slika8.jpeg',
    'slike/slika9.png',
    'slike/slika10.jpeg',
    'slike/slika11.jpeg',
    'slike/slika12.jpeg',
    'slike/slika13.png',
    'slike/slika14.jpg',
    'slike/slika15.jpg',
    'slike/slika16.png',
    'slike/slika17.jpeg',
    'slike/slika18.jpeg',
    'slike/slika19.png',
    'slike/slika20.png',
    'slike/slika21.jpg',
    'slike/slika22.jpg',
    'slike/slika23.jpg',
    'slike/slika24.jpg',
    'slike/slika25.jpg',
    'slike/slika26.jpeg',
    'slike/slika27.jpeg',
    'slike/slika28.jpg',
    'slike/slika29.jpg',
    'slike/slika30.jpg',
    'slike/slika31.jpg',
    'slike/slika32.jpg',
    'slike/slika33.jpg',
    'slike/slika34.jpeg',
    'slike/slika35.png',
    'slike/slika36.jpeg',
    'slike/slika37.png',
    'slike/slika38.png',
    'slike/slika39.png',
    'slike/slika40.jpeg',
    'slike/slika41.jpeg',
    'slike/slika42.jpg',
    'slike/slika43.jpeg',
    'slike/slika44.jpg',
    'slike/slika45.jpeg',
    'slike/slika46.jpg',
    'slike/slika47.png',
    'slike/slika48.jpeg',
    'slike/slika49.jpeg',
    'slike/slika50.jpg',
    'slike/slika51.jpg',
    'slike/slika52.jpeg',
    'slike/slika53.png',
    'slike/slika54.jpg',
    'slike/slika55.jpeg',
    'slike/slika56.jpg',
    'slike/slika57.jpeg',
    'slike/slika58.jpg',
    'slike/slika59.jpg'
];

slike.forEach(slika => {
    const img = document.createElement('img');
    img.src = slika;
    slikeContainer.appendChild(img);
});
